git: github
topology:
  type: gcp
settings:
  cosmos_name: cosmos-demo-20
  cosmos_project: cosmos-demo-20
  bucket_name: cosmos-demo-20-gcs
  bucket_region: eu
foundations:
  default_visibility: public
  default_owner: cx-soral
  default_tpl_owner: x-i-a
  default_tpl_name: xia-template-foundation
structure:
  foundations:
    foundation-demo-20:

