name: Workflow

on:
  push:
    tags:
    - '*'

jobs:
  test-local:
    if: true
    runs-on: ubuntu-latest
    steps:
    - id: checkout-code
      uses: actions/checkout@v4

  build:
    if: true
    runs-on: ubuntu-latest
    needs: test-local

    steps:
    - id: checkout-code
      uses: actions/checkout@v4
  deploy:
    if: true
    runs-on: ubuntu-latest
    needs: build

    permissions:
      contents: read
      id-token: write
    steps:
    - id: checkout-code
      uses: actions/checkout@v4
    - id: prepare-modules
      name: Prepare modules
      run: |
        pip install xia-framework xia-module
        python -m xia_framework.cosmos plan

    - id: auth-gcp-oidc
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        project_id: ${{ vars.PROJECT_ID }}
        workload_identity_provider: ${{ vars.SECRET_WIP_NAME }}
        service_account: ${{ vars.PROVIDER_SA_EMAIL }}

    - id: terraform-apply
      name: Apply Terraform
      uses: x-i-a/action-gcs-terraform-apply@main
      with:
        tf_bucket_name: ${{ vars.tf_bucket_name }}
        cosmos_name: ${{ vars.cosmos_name }}

  test-remote:
    if: true
    runs-on: ubuntu-latest
    needs: deploy

    steps:
    - id: checkout-code
      uses: actions/checkout@v4
  publish:
    if: true
    runs-on: ubuntu-latest
    needs: test-remote
    steps:
    - id: checkout-code
      uses: actions/checkout@v4
